#ifndef DILITHIUM_PARAMS_H
#define DILITHIUM_PARAMS_H

#define DILITHIUM_SEEDBYTES 32U
#define DILITHIUM_CRHBYTES 48U
#define DILITHIUM_N 256U
#define DILITHIUM_Q 8380417U
#define DILITHIUM_QBITS 23U
#define DILITHIUM_ROOT_OF_UNITY 1753U
#define DILITHIUM_D 14U
#define DILITHIUM_GAMMA1 ((DILITHIUM_Q - 1U)/16U)
#define DILITHIUM_GAMMA2 (DILITHIUM_GAMMA1/2U)
#define DILITHIUM_ALPHA (2U*DILITHIUM_GAMMA2)

#endif
