#ifndef DILITHIUM_PARAMS_H
#define DILITHIUM_PARAMS_H

#ifndef MODE
#define DILITHIUM_MODE 2
#endif

#define DILITHIUM_SEEDBYTES 32U
#define DILITHIUM_CRHBYTES 48U
#define DILITHIUM_N 256U
#define DILITHIUM_Q 8380417U
#define DILITHIUM_QBITS 23U
#define DILITHIUM_ROOT_OF_UNITY 1753U
#define DILITHIUM_D 14U
#define DILITHIUM_GAMMA1 ((Q - 1U)/16U)
#define DILITHIUM_GAMMA2 (DILITHIUM_GAMMA1/2U)
#define DILITHIUM_ALPHA (2U*DILITHIUM_GAMMA2)

#if MODE == 0
#define DILITHIUM_K 3U
#define DILITHIUM_L 2U
#define DILITHIUM_ETA 7U
#define DILITHIUM_SETABITS 4U
#define DILITHIUM_BETA 375U
#define DILITHIUM_OMEGA 64U

#elif MODE == 1
#define DILITHIUM_K 4U
#define DILITHIUM_L 3U
#define DILITHIUM_ETA 6U
#define DILITHIUM_SETABITS 4U
#define DILITHIUM_BETA 325U
#define DILITHIUM_OMEGA 80U

#elif MODE == 2
#define DILITHIUM_K 5U
#define DILITHIUM_L 4U
#define DILITHIUM_ETA 5U
#define DILITHIUM_SETABITS 4U
#define DILITHIUM_BETA 275U
#define DILITHIUM_OMEGA 96U

#elif MODE == 3
#define DILITHIUM_K 6U
#define DILITHIUM_L 5U
#define DILITHIUM_ETA 3U
#define DILITHIUM_SETABITS 3U
#define DILITHIUM_BETA 175U
#define DILITHIUM_OMEGA 120U

#endif

#define DILITHIUM_POL_SIZE_PACKED ((DILITHIUM_N*DILITHIUM_QBITS)/8)
#define DILITHIUM_POLT1_SIZE_PACKED ((DILITHIUM_N*(DILITHIUM_QBITS - DILITHIUM_D))/8)
#define DILITHIUM_POLT0_SIZE_PACKED ((DILITHIUM_N*DILITHIUM_D)/8)
#define DILITHIUM_POLETA_SIZE_PACKED ((DILITHIUM_N*DILITHIUM_SETABITS)/8)
#define DILITHIUM_POLZ_SIZE_PACKED ((DILITHIUM_N*(DILITHIUM_QBITS - 3))/8)
#define DILITHIUM_POLW1_SIZE_PACKED ((DILITHIUM_N*4)/8)
#define DILITHIUM_POLVECK_SIZE_PACKED (DILITHIUM_K*DILITHIUM_POL_SIZE_PACKED)
#define DILITHIUM_POLVECL_SIZE_PACKED (DILITHIUM_L*DILITHIUM_POL_SIZE_PACKED)

#define DILITHIUM_CRYPTO_PUBLICKEYBYTES (DILITHIUM_SEEDBYTES + DILITHIUM_K*DILITHIUM_POLT1_SIZE_PACKED)
#define DILITHIUM_CRYPTO_SECRETKEYBYTES (2*DILITHIUM_SEEDBYTES + (DILITHIUM_L + DILITHIUM_K)*DILITHIUM_POLETA_SIZE_PACKED + DILITHIUM_CRHBYTES + DILITHIUM_K*DILITHIUM_POLT0_SIZE_PACKED)
#define DILITHIUM_CRYPTO_BYTES (DILITHIUM_L*DILITHIUM_POLZ_SIZE_PACKED + (DILITHIUM_OMEGA + DILITHIUM_K) + (DILITHIUM_N/8 + 8))

#endif
