#ifndef LDAA_PARAMS_H
#define LDAA_PARAMS_H

// Weak Security Parameters
#define LDAA_WEAK_M        13UL
#define LDAA_WEAK_Q        3329UL
#define LDAA_WEAK_N        128UL
#define LDAA_WEAK_S        2UL
#define LDAA_WEAK_L        3UL
#define LDAA_WEAK_C        4UL
#define LDAA_WEAK_LOG_BETA 3UL
#define LDAA_WEAK_LOG_W    2UL
#define LDAA_WEAK_K_COMM   3UL
#define LDAA_WEAK_ALPHA2   4UL

#define LDAA_WEAK_COMMIT1_LENGTH (4UL + 4UL * (2UL * (1UL << LDAA_WEAK_LOG_W) - 1UL) * \
        LDAA_WEAK_LOG_BETA)
#define LDAA_WEAK_COMMIT2_LENGTH ((2UL * (1UL << LDAA_WEAK_LOG_W) - 1UL) * LDAA_WEAK_LOG_BETA * \
        (LDAA_WEAK_M * (2UL * LDAA_WEAK_L + 3UL) + 1UL) + 2UL)
#define LDAA_WEAK_COMMIT3_LENGTH LDAA_WEAK_COMMIT2_LENGTH

#define LDAA_WEAK_SECRET_KEY_LENGTH (LDAA_WEAK_M*LDAA_WEAK_N) // Column of LDAA_N polynomials
#define LDAA_WEAK_PUBLIC_KEY_LENGTH LDAA_WEAK_N // polynomial
#define LDAA_WEAK_ISSUER_BNTT_LENGTH (LDAA_WEAK_COMMIT1_LENGTH * LDAA_WEAK_K_COMM)
#define LDAA_WEAK_ISSUER_BNTT2_LENGTH (LDAA_WEAK_COMMIT2_LENGTH * LDAA_WEAK_K_COMM)
#define LDAA_WEAK_C1_LENGTH (LDAA_WEAK_COMMIT1_LENGTH * LDAA_WEAK_N * 4)
#define LDAA_WEAK_C2_LENGTH (LDAA_WEAK_COMMIT2_LENGTH * LDAA_WEAK_N * 4)
#define LDAA_WEAK_C3_LENGTH (LDAA_WEAK_COMMIT3_LENGTH * LDAA_WEAK_N * 4)

// Medium Security Parameters
#define LDAA_MEDIUM_M        24UL
#define LDAA_MEDIUM_Q        8380417UL
#define LDAA_MEDIUM_N        256UL
#define LDAA_MEDIUM_S        6UL
#define LDAA_MEDIUM_L        32UL
#define LDAA_MEDIUM_C        8UL
#define LDAA_MEDIUM_LOG_BETA 8UL
#define LDAA_MEDIUM_LOG_W    1UL
#define LDAA_MEDIUM_K_COMM   64UL
#define LDAA_MEDIUM_ALPHA2   10UL

#define LDAA_MEDIUM_COMMIT1_LENGTH (4UL + 4UL * (2UL * (1UL << LDAA_MEDIUM_LOG_W) - 1UL) * \
        LDAA_MEDIUM_LOG_BETA)
#define LDAA_MEDIUM_COMMIT2_LENGTH ((2UL * (1UL << LDAA_MEDIUM_LOG_W) - 1UL) * LDAA_MEDIUM_LOG_BETA * \
        (LDAA_MEDIUM_M * (2UL * LDAA_MEDIUM_L + 3UL) + 1UL) + 2UL)
#define LDAA_MEDIUM_COMMIT3_LENGTH LDAA_MEDIUM_COMMIT2_LENGTH

#define LDAA_MEDIUM_SECRET_KEY_LENGTH (LDAA_MEDIUM_M*LDAA_MEDIUM_N) // Column of LDAA_N polynomials
#define LDAA_MEDIUM_PUBLIC_KEY_LENGTH LDAA_MEDIUM_N // polynomial
#define LDAA_MEDIUM_ISSUER_BNTT_LENGTH (LDAA_MEDIUM_COMMIT1_LENGTH * LDAA_MEDIUM_K_COMM)
#define LDAA_MEDIUM_ISSUER_BNTT2_LENGTH (LDAA_MEDIUM_COMMIT2_LENGTH * LDAA_MEDIUM_K_COMM)
#define LDAA_MEDIUM_C1_LENGTH (LDAA_MEDIUM_COMMIT1_LENGTH * LDAA_MEDIUM_N * 4)
#define LDAA_MEDIUM_C2_LENGTH (LDAA_MEDIUM_COMMIT2_LENGTH * LDAA_MEDIUM_N * 4)
#define LDAA_MEDIUM_C3_LENGTH (LDAA_MEDIUM_COMMIT3_LENGTH * LDAA_MEDIUM_N * 4)

// High Security Parameters
#define LDAA_HIGH_M        24UL
#define LDAA_HIGH_Q        8380417UL
#define LDAA_HIGH_N        512UL
#define LDAA_HIGH_S        6UL
#define LDAA_HIGH_L        32UL
#define LDAA_HIGH_C        8UL
#define LDAA_HIGH_LOG_BETA 8UL
#define LDAA_HIGH_LOG_W    1UL
#define LDAA_HIGH_K_COMM   64UL
#define LDAA_HIGH_ALPHA2   10UL

#define LDAA_HIGH_COMMIT1_LENGTH (4UL + 4UL * (2UL * (1UL << LDAA_HIGH_LOG_W) - 1UL) * \
        LDAA_HIGH_LOG_BETA)
#define LDAA_HIGH_COMMIT2_LENGTH ((2UL * (1UL << LDAA_HIGH_LOG_W) - 1UL) * LDAA_HIGH_LOG_BETA * \
        (LDAA_HIGH_M * (2UL * LDAA_HIGH_L + 3UL) + 1UL) + 2UL)
#define LDAA_HIGH_COMMIT3_LENGTH LDAA_HIGH_COMMIT2_LENGTH

#define LDAA_HIGH_SECRET_KEY_LENGTH (LDAA_HIGH_M*LDAA_HIGH_N) // Column of LDAA_N polynomials
#define LDAA_HIGH_PUBLIC_KEY_LENGTH LDAA_HIGH_N // polynomial
#define LDAA_HIGH_ISSUER_BNTT_LENGTH (LDAA_HIGH_COMMIT1_LENGTH * LDAA_HIGH_K_COMM)
#define LDAA_HIGH_ISSUER_BNTT2_LENGTH (LDAA_HIGH_COMMIT2_LENGTH * LDAA_HIGH_K_COMM)
#define LDAA_HIGH_C1_LENGTH (LDAA_HIGH_COMMIT1_LENGTH * LDAA_HIGH_N * 4)
#define LDAA_HIGH_C2_LENGTH (LDAA_HIGH_COMMIT2_LENGTH * LDAA_HIGH_N * 4)
#define LDAA_HIGH_C3_LENGTH (LDAA_HIGH_COMMIT3_LENGTH * LDAA_HIGH_N * 4)

#endif
